# utils/ppt_generator.py

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
from pptx.dml.color import RGBColor

def create_ppt(summary_text, filename="Research_Summary.pptx"):
    summary_points = summary_text.split("\n\n")

    prs = Presentation()
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = "Research Paper Summary"
    title_slide.placeholders[1].text = "Auto-generated by AI Summarizer"

    bullet_slide_layout = prs.slide_layouts[1]

    for i, point in enumerate(summary_points):
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        shapes.title.text = f"Point {i+1}"

        text_frame = shapes.placeholders[1].text_frame
        text_frame.clear()
        p = text_frame.paragraphs[0]
        p.text = point
        p.font.size = Pt(18)
        p.font.color.rgb = RGBColor(40, 40, 40)

    prs.save(filename)
    return filename
